modLoader = "javafml"
loaderVersion = "[47,)"
license = "CC0-1.0"

[[mods]]
modId = "foodtweaker"
version = "${version}"
displayName = "FoodTweaker"
authors = "icywhenhot"
logoFile = "assets/foodtweaker/icon.png"
description = '''
Config-driven overrides for food stats (nutrition, saturation, eat speed, always-edible, and on-eat effects) of any vanilla or modded item.
'''

[[dependencies.foodtweaker]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foodtweaker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foodtweaker]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
